site_name: FemmeAura Docs
site_url: https://your-github-username.github.io/FemmeAura/
theme:
  name: material
  logo: FemmeAura Logo.png
  palette:
    primary: purple
    accent: pink
nav:
  - Home: index.md
  - Contributing: contributing.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-github-username/FemmeAura
